# Staging Environment Configuration Override
environment: staging
debug: true

# Staging logging settings
logging:
  level: "DEBUG"
  file_enabled: true
  file_path: "logs/staging/crypto_collector.log"
  console_enabled: true
  max_file_size: 200
  backup_count: 7

# Staging performance settings
performance:
  enable_metrics: true
  metrics_interval: 45.0
  enable_profiling: true
  max_memory_usage: 3072
  max_cpu_usage: 75.0

# Staging intervals (moderate frequency)
ticker_interval: 20.0
funding_rate_interval: 240.0

# Staging cache settings
cache:
  enabled: true
  default_ttl: 450.0
  max_size: 25000
  cleanup_interval: 90.0

# Staging batch settings
batch:
  enabled: true
  max_size: 200
  max_wait_time: 3.0
  strategy: "time_based"
  compression_enabled: true

# Staging circuit breaker (balanced)
exchange_configs:
  binance:
    circuit_breaker:
      failure_threshold: 4
      recovery_timeout: 45.0
      success_threshold: 2
      timeout: 20.0
      max_failure_threshold: 12
      backoff_multiplier: 1.8
      max_recovery_timeout: 240.0
    retry:
      max_attempts: 4
      base_delay: 0.8
      max_delay: 20.0
      strategy: "adaptive"
    health_check:
      check_interval: 90.0
      timeout: 20.0
      failure_threshold: 2
      recovery_threshold: 1

# Staging database (enabled for testing)
database:
  enabled: true
  host: "staging-db.local"
  port: 9000
  database: "crypto_data_staging"
  user: "staging_user"
